### ISSUE TITLE
Unresolvable Dependency on ramsey/uuid 3.0.* w/Composer

### ISSUE THREAD

**Issue by humbugz** [dave-redfern/laravel-doctrine-tenancy#4]
@dave-redfern I'm exploring your package for use in a Laravel multi-tenant site and found that at the moment it cannot be installed via Composer due to laravel-doctrine-behaviours requiring ramsey/uuid 3._0_.* while ramsey/uuid is currently locked to 3._5_.2.

Thanks!

**Comment by dave-redfern** [comment]
@humbugz Thanks for the heads up; I'll check and update the dependencies, hopefully tonight, but it might have to be tomorrow.

**Comment by dave-redfern** [comment]
@humbugz I've changed the ramsey/uuid dependency in behaviours to ^3.0 (somnambulist/laravel-doctrine-behaviours:0.5.1), could you confirm that this resolves the dependency problem you had? Thanks!

**Comment by humbugz** [comment]
@dave-redfern thanks for the fix! I can confirm Composer is happy again.

**Comment by dave-redfern** [comment]
@humbugz Glad to hear that. Let me know if you have any issues with the tenancy package.
