### ISSUE TITLE
Not compatible with Laravel framework v5.7.29

### ISSUE THREAD

**Issue by chrisnoden** [dave-redfern/laravel-doctrine-tenancy#5]
Somnambulist\Tenancy\View\FileViewFinder::setPaths is not compatible with Illuminate\View\FileViewFinder::setP
  aths($paths)

Framework method is:
```
    /**
     * Set the active view paths.
     *
     * @param  array  $paths
     * @return $this
     */
    public function setPaths($paths)
    {
        $this->paths = $paths;

        return $this;
    }
```

**Comment by dave-redfern** [comment]
This was fixed in 0.7.0. As the versions are below 1.0, `composer update` will not update versions tagged as e.g. ^0.6. That would allow versions between 0.6 and <0.7. You would need to explicitly update the composer.json to allow version 0.7.0.
