### ISSUE TITLE
Laravel 8 TenantRouteResolver map method is not called

### ISSUE THREAD

**Issue by westcomputerconsultancy** [dave-redfern/laravel-doctrine-tenancy#7]
Hello,

Thank you for this package. 

I have everything else working (I think) with this very useful package. However, the Laravel 8 routing has changed quite a bit, and I think that's broken the TenantRouteResolver service provider. The map method no longer seems to be called and so the tenant routes are not being registered. I'm not confident enough with the Laravel framework to understand all the complexities. I don't think I'm doing anything wrong. Have you see the same problem in Laravel 8?

I've found I can load the routes by adding 

```
if ($this->routesAreCached()) {
            $this->loadCachedRoutes();
        } else {
            $this->loadRoutes();
            $this->app['router']->getRoutes()->refreshNameLookups();
            $this->app['router']->getRoutes()->refreshActionLookups();
        //$routes = $this->app->call([$this, 'map']);
        }
```

(taken from Illuminate\Foundation\Support\Providers\RouteServiceProvider)
to the boot method in TenantRouteResolver but this doesn't really seem to make the routes available, and any further than this I'm a little out of my depth.

Thanks,

Stephen

**Comment by westcomputerconsultancy** [comment]
A little bit more of an update. 

In TenantRouteResolver adding to the end of the boot method in TenantRouteResolver 

`$this->app->call([$this, 'map']);`

registers the routes but then the routes aren't available by name in the views, so, for instance, I have a route named searches.search which is referenced in my welcome page. The welcome page loads, but the view fails with 

Route [searches.search] not defined

So the routes are registered but not available later.

**Comment by westcomputerconsultancy** [comment]
I have a fix that works for me. I've only tested it for my set up though, so I shan't do a PR. It's at 

https://github.com/westcomputerconsultancy/laravel-doctrine-tenancy/blob/master/src/Http/Middleware/TenantRouteResolver.php

**Comment by dave-redfern** [comment]
@westcomputerconsultancy I'm afraid I've not had much time to look into updating the internals yet of this package. One to check: the tenancy route provider cannot be used with the laravel route provider. If you haven't already removed that, then you would need to ensure that the laravel route provider is commented out or deleted from your config/app.php file.

Now in terms of the setup: it looks like the functionality was moved from the boot() method to registering a callback in the register() method. This is likely what is causing the fundamental issue of the routes not registering. In theory; the old behaviour should be restorable by adding a blank `register()` method in your version of the route provider. Otherwise, the register method would need replacing and the logic updating to use the alternative implementations. Essentially that means moving the config processing as the first set of calls in the at callback. Potentially something like the following:

```
    public function register()
    {
        $this->booted(function () {
            foreach ($this->app->make('config')->get('tenancy.multi_site.router.patterns', []) as $name => $pattern) {
                $this->app->make('router')->pattern($name, $pattern);
            }

            if ($this->routesAreCached()) {
                $this->loadCachedRoutes();
            } else {
                $this->loadRoutes();

                $this->app->booted(function () {
                    $this->app['router']->getRoutes()->refreshNameLookups();
                    $this->app['router']->getRoutes()->refreshActionLookups();
                });
            }
        });
    }
```
I'm not sure that is enough, but hopefully it might help!

**Comment by dave-redfern** [comment]
@westcomputerconsultancy Actually updating the route resolver to have the following:

```
    public function register()
    {

    }

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        foreach ($this->app->make('config')->get('tenancy.multi_site.router.patterns', []) as $name => $pattern) {
            $this->app->make('router')->pattern($name, $pattern);
        }

        $this->setRootControllerNamespace();

        if ($this->routesAreCached()) {
            $this->loadCachedRoutes();
        } else {
            $this->loadRoutes();

            $this->app->booted(function () {
                $this->app['router']->getRoutes()->refreshNameLookups();
                $this->app['router']->getRoutes()->refreshActionLookups();
            });
        }
    }
```

does get the basic tests to pass so it might work - provided that the it is registered as a route middleware and not as a service provider (has to be delayed as long as possible to allow for the tenant resolution to work).

**Comment by dave-redfern** [comment]
@westcomputerconsultancy I have been able to update the package and added several more tests and appears to function correctly with Laravel 8. I can push this up as a dev-master if you are interested in testing it?

**Comment by westcomputerconsultancy** [comment]
Thanks ever so much for that, looking at the problem and your previous
replies.

Yes please. I would much prefer to use your version rather than my fork.

**Comment by dave-redfern** [comment]
@westcomputerconsultancy I've pushed my changes to master so if you change your composer dependency to reference `dev-master` you should be able to try it out.

I've shifted a fair bit around from the last release, in particular:
 * no doctrine event subscriber - inject tenancy on creation
 * traits now live in `Entities\Concerns`
 * internally a bunch of classes have been removed
 * URL parameters are now injected into the default URL generator (tenant_owner_id and tenant_creator_id) so provided the tenant can be resolved they will always be available, but can be injected to override the current tenant.

The tests all run against Laravel 8 and it appears to work - at least in the limited test cases. I have yet to add tests for the auth checks, but will get to that when I can.

Let me know how you get on!

**Comment by westcomputerconsultancy** [comment]
Many thanks for this. Once I've finished the part of the project I'm on,
I'll swap my fork to your dev-master and make any changes necessary for the
restructuring. For my project I've also added (to new middleware)

Lang::addNamespace('tenant', app('path.lang') . '/' .
app('auth.tenant')->getTenantOwner()->getDomain());

This means that each tenant will be able to have a set of language
files for the loaded tenant in

resources/lange/{tenantdomain}/en/

I don't know if you'd be interested in adding that to your middleware?

**Comment by dave-redfern** [comment]
@westcomputerconsultancy I can add that; shouldn't be too much trouble. So far I have not needed custom language per tenant and instead either share the language files across the site or embed the specific text directly in the template files for that tenant; though for multi-accounts on a single site I can see how that would be problematic.

**Comment by westcomputerconsultancy** [comment]
Only do it if you feel it might be useful. I have written middleware that
registers it so it's not problem to me if you prefer not to.

I have sites in development using the package that have identical templates
but the text is just slightly different - one or two words changed -
depending upon the tenant, so it is of huge important to me, but not
necessarily anyone else.

**Comment by dave-redfern** [comment]
I'm looking at it, and it does raise some issues because if I implement it, it would need to register both the current tenant and the owner if it is different. The registered namespaces would need to be different in that instance and I think that would cause issues with the translations.

**Comment by westcomputerconsultancy** [comment]
Ah. I see. Don't worry then. My implementation is less complex so that
wouldn't affect me. I'm best to keep my current middleware rather than
cause you complications.

**Comment by westcomputerconsultancy** [comment]
I've installed the latest version from dev-master, updated the namespaces
and all seems fine now. Thanks every so much.

**Comment by westcomputerconsultancy** [comment]
All working well now. Thanks for the latest commits. I'll keep checking for the next tagged release.

**Comment by dave-redfern** [comment]
@westcomputerconsultancy I've been testing it on my own website (in dev at least) to check for issues and for me too, it appears to be working well. In that case, I'll tag a new major release.

Thanks for your time and efforts!

**Comment by westcomputerconsultancy** [comment]
Fantastic. Thank YOU.

**Comment by dave-redfern** [comment]
@westcomputerconsultancy tagged a 1.0.0 release. Let me know if you run into any further issues!
